### ISSUE TITLE
Apply GUI design to the empty case

### ISSUE THREAD

**Issue by xpdlf1004** [CodeChain-io/codechain-wallet#13]
![image](https://user-images.githubusercontent.com/3959505/49487848-9d695700-f887-11e8-9896-cba57cc4e32a.png)

**Comment by tammy17** [comment]
<img width="751" alt="2018-12-05 4 04 31" src="https://user-images.githubusercontent.com/44084194/49495786-8f2b3300-f8a7-11e8-80c1-b63d040deb18.png">

**Comment by xpdlf1004** [comment]
Merged
